### PR TITLE
feat(segments): add compound metrics

### PR DESCRIPTION
**Pull request by rhiroyuki**
Added:
- third_party_id
- compound metrics

Added metrics:
```
      bot_clicks
      bot_decision_win_clicks
      bot_decision_win_impressions
      bot_impressions
      bot_loaded_clicks
      bot_loaded_impressions
      decision_win_clicks
      loaded_clicks
      non_bot_clicks
      non_bot_decision_win_clicks
      non_bot_decision_win_impressions
      non_bot_impressions
      non_bot_loaded_clicks
      non_bot_loaded_impressions
      non_viewable_bot_decision_win_clicks
      non_viewable_bot_decision_win_impressions
      non_viewable_bot_loaded_clicks
      non_viewable_bot_loaded_impressions
      non_viewable_clicks
      non_viewable_decision_win_clicks
      non_viewable_decision_win_impressions
      non_viewable_impressions
      non_viewable_loaded_clicks
      non_viewable_loaded_impressions
      non_viewable_non_bot_clicks
      non_viewable_non_bot_decision_win_clicks
      non_viewable_non_bot_decision_win_impressions
      non_viewable_non_bot_impressions
      non_viewable_non_bot_loaded_clicks
      non_viewable_non_bot_loaded_impressions
      viewable_bot_clicks
      viewable_bot_decision_win_clicks
      viewable_bot_decision_win_impressions
      viewable_bot_impressions
      viewable_bot_loaded_clicks
      viewable_bot_loaded_impressions
      viewable_clicks
      viewable_decision_win_clicks
      viewable_decision_win_impressions
      viewable_impressions
      viewable_loaded_clicks
      viewable_loaded_impressions
      viewable_non_bot_clicks
      viewable_non_bot_decision_win_clicks
      viewable_non_bot_decision_win_impressions
      viewable_non_bot_impressions
      viewable_non_bot_loaded_clicks
      viewable_non_bot_loaded_impressions
```
ENG-985

### CODE REVIEW

**Comment by oPauloChaves** [comment]
Looks great! :+1:

**Comment by enddynayn** [comment]
👍 beautiful

**Comment by eching** [comment]
👍

**Comment by guivinicius** [comment]
👍

**Pull request merged**
